theme: jekyll-theme-midnight
title: Welcome to the Bartos Nicolas homepage
description: Découvrez mes supers projets comme la gestion des candidatures, la resolution de labyrinthe, un BomberMan en Javascript ou bien un jeu de mémoires.
